name: News Service Lib

on: [push]

jobs:
  lib-CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint and check score
        run: pylint-fail-under --fail_under 9  --ignore=README.md,requirements.txt ./*
      - name: Test with unittest
        run: coverage run --source ./news_service_lib --branch --omit=*__init__**,**tests**,**graphql/model** -m unittest discover -v news_service_lib/tests -t .
      - name: Check test coverage
        run: coverage report  --fail-under=80
      - name: Generate coverage report
        run: coverage xml -o coverage_lib.xml
      - name: Codecov upload
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage_lib.xml
      - name: Build the library
        run: python setup.py bdist_wheel
